 version: '3.8'
 services:
   php-microservice-rabbitmq-test:
      image: rabbitmq:3.10.7-management-alpine
      container_name: php-microservice-rabbitmq-test
      hostname: php-microservice-rabbitmq-test
      environment:
         RABBITMQ_DEFAULT_USER: guest
         RABBITMQ_DEFAULT_PASS: guest
         RABBITMQ_DEFAULT_VHOST: test
      tty: true
      healthcheck:
         test: "exit 0"
   
   micro_consumer:
      build:
         context: ./
         dockerfile: ./docker/Dockerfile
         network: host
      image: php-microservice-test:latest
      entrypoint: ["/app/vendor/bin/phpunit", "--testsuite", "Consumer"]
      init: true
      tty: true
      depends_on:
         php-microservice-rabbitmq-test:
            condition: service_healthy

   micro:
      image: php-microservice-test:latest
      entrypoint: ["/app/vendor/bin/phpunit", "--testsuite", "Unit,Functional"]
      init: true
      tty: true
      depends_on:
         - micro_consumer