#!/bin/bash -i

php ./vendor/bin/php-cs-fixer fix --show-progress=dots

php ./vendor/bin/phplint

php ./vendor/bin/psalm #--show-info=true

#php vendor/bin/phpunit --testsuit Unit
#docker-compose up --build --exit-code-from micro micro

#docker run --rm -v $PWD:/code montealegreluis/phuml phuml:diagram -r -o -a -b -e classic -p dot src diagram.png
#docker run --rm -v $PWD:/code montealegreluis/phuml phuml:dot -r -a -i -o src diagram.gv
#docker run --rm -v $PWD:/code montealegreluis/phuml phuml:statistics -r src diagram.txt