#!/bin/bash -i

php ./vendor/bin/php-cs-fixer fix --show-progress=dots

php ./vendor/bin/phplint

php ./vendor/bin/psalm

php vendor/bin/phpunit --testsuit Unit
#docker-compose up --build --exit-code-from micro micro