name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker-compose build
    - name: Run test
      run: docker-compose up micro
